name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Gradle
        run: |
#          ./gradlew build jacocoTestReport jacocoTestCoverageVerification --stacktrace --info --warning-mode all
           ./gradlew build jacocoTestReport --stacktrace --info --warning-mode all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: Test Reports
          path: build/reports/tests/test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Reports
          path: build/reports/jacoco/test

      - name: Display Test Results
        run: |
          echo "Test Results Summary:"
          cat build/test-results/test/*.xml

      - name: Display Coverage Summary
        run: |
          echo "Coverage Statistics:"
          cat build/reports/jacoco/test/jacocoTestReport.xml | grep -E "<counter|LINE|BRANCH"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests
          verbose: true